### ISSUE TITLE
Error executing command: Error

### ISSUE THREAD

**Issue by kirantpatil** [maggu2810/smarthome-packaging-sample-karaf#5]
I tried to install "esh-ui-classic" as below and it is showing error.

Environment:

```
$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

$ echo $JAVA_HOME
/usr/lib/jvm/java-8-oracle

$ cat /etc/issue
Ubuntu 14.04.5 LTS \n \l

```
Karaf command output

```
karaf@root()> feature:install esh-ui-classic
Error executing command: Error

karaf@root()> bundle:list | grep classic*
karaf@root()> 
```

**Comment by maggu2810** [comment]
It seems to work for @amarpulli544 and me (I tried it again now).
So, I don't think there is an error in the packaging (that is what this project is used for only, see please: https://github.com/maggu2810/smarthome-packaging-sample-karaf/issues/4#issuecomment-277926668)

I assume it is system related.

First you should check your log (`log:display`, `log:tail`, ...)
I would expect that there are relevant messages.
You could check if you can install other (non ESH features), too.

**Comment by maggu2810** [comment]
Regardless of the wrong issue tracker, you could insert your log output and I try to have a look at... But I close the issue as it is not a packaging problem and so really off-topic.

**Comment by kirantpatil** [comment]
I am getting below error in log.

2017-02-13 10:46:15,446 | ERROR | nsole user karaf | ShellUtil                        | 77 - org.apache.karaf.shell.core - 4.0.7 | Exception caught while executing command
org.apache.karaf.features.internal.util.MultiException: Error
	at org.apache.karaf.features.internal.download.impl.MavenDownloadManager$MavenDownloader.<init>(MavenDownloadManager.java:84)[8:org.apache.karaf.features.core:4.0.7]
	at org.apache.karaf.features.internal.download.impl.MavenDownloadManager.createDownloader(MavenDownloadManager.java:72)[8:org.apache.karaf.features.core:4.0.7]
	at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:363)[8:org.apache.karaf.features.core:4.0.7]
	at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:360)[8:org.apache.karaf.features.core:4.0.7]
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:187)[8:org.apache.karaf.features.core:4.0.7]
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:263)[8:org.apache.karaf.features.core:4.0.7]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1176)[8:org.apache.karaf.features.core:4.0.7]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1074)[8:org.apache.karaf.features.core:4.0.7]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)[:1.7.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)[:1.7.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)[:1.7.0_121]
	at java.lang.Thread.run(Thread.java:745)[:1.7.0_121]
Caused by: java.io.IOException: Error downloading mvn:org.eclipse.smarthome.extension.ui/org.eclipse.smarthome.ui.classic/0.9.0-SNAPSHOT
	at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:67)[8:org.apache.karaf.features.core:4.0.7]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)[:1.7.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)[:1.7.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)[:1.7.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)[:1.7.0_121]
	... 3 more
**Caused by: java.io.IOException: Error resolving artifact org.eclipse.smarthome.extension.ui:org.eclipse.smarthome.ui.classic:jar:0.9.0-SNAPSHOT: Could not find artifact org.eclipse.smarthome.extension.ui:org.eclipse.smarthome.ui.classic:jar:0.9.0-SNAPSHOT in apache (http://repository.apache.org/content/groups/snapshots-group/)**
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:661)[7:org.ops4j.pax.url.mvn:2.4.7]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:598)[7:org.ops4j.pax.url.mvn:2.4.7]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:576)[7:org.ops4j.pax.url.mvn:2.4.7]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:550)[7:org.ops4j.pax.url.mvn:2.4.7]
	at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:34)[8:org.apache.karaf.features.core:4.0.7]
	at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:58)[8:org.apache.karaf.features.core:4.0.7]
	... 7 more

**Comment by kirantpatil** [comment]
For installing basic-ui, I am getting below error.

2017-02-13 10:53:51,027 | ERROR | nsole user karaf | ShellUtil                        | 77 - org.apache.karaf.shell.core - 4.0.7 | Exception caught while executing command
org.apache.karaf.features.internal.util.MultiException: Error
	at org.apache.karaf.features.internal.download.impl.MavenDownloadManager$MavenDownloader.<init>(MavenDownloadManager.java:84)[8:org.apache.karaf.features.core:4.0.7]
	at org.apache.karaf.features.internal.download.impl.MavenDownloadManager.createDownloader(MavenDownloadManager.java:72)[8:org.apache.karaf.features.core:4.0.7]
	at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:363)[8:org.apache.karaf.features.core:4.0.7]
	at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:360)[8:org.apache.karaf.features.core:4.0.7]
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:187)[8:org.apache.karaf.features.core:4.0.7]
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:263)[8:org.apache.karaf.features.core:4.0.7]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1176)[8:org.apache.karaf.features.core:4.0.7]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1074)[8:org.apache.karaf.features.core:4.0.7]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)[:1.7.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)[:1.7.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)[:1.7.0_121]
	at java.lang.Thread.run(Thread.java:745)[:1.7.0_121]
Caused by: java.io.IOException: Error downloading mvn:org.eclipse.smarthome.extension.ui/org.eclipse.smarthome.ui.basic/0.9.0-SNAPSHOT
	at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:67)[8:org.apache.karaf.features.core:4.0.7]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)[:1.7.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)[:1.7.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)[:1.7.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)[:1.7.0_121]
	... 3 more
**Caused by: java.io.IOException: Error resolving artifact org.eclipse.smarthome.extension.ui:org.eclipse.smarthome.ui.basic:jar:0.9.0-SNAPSHOT: Could not find artifact org.eclipse.smarthome.extension.ui:org.eclipse.smarthome.ui.basic:jar:0.9.0-SNAPSHOT in apache (http://repository.apache.org/content/groups/snapshots-group/)**
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:661)[7:org.ops4j.pax.url.mvn:2.4.7]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:598)[7:org.ops4j.pax.url.mvn:2.4.7]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:576)[7:org.ops4j.pax.url.mvn:2.4.7]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:550)[7:org.ops4j.pax.url.mvn:2.4.7]
	at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:34)[8:org.apache.karaf.features.core:4.0.7]
	at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:58)[8:org.apache.karaf.features.core:4.0.7]
	... 7 more

karaf@root()>

**Comment by maggu2810** [comment]
So, the artifacts could not be resolved / fetched from external:

```
Caused by: java.io.IOException: Error resolving artifact org.eclipse.smarthome.extension.ui:org.eclipse.smarthome.ui.classic:jar:0.9.0-SNAPSHOT: Could not find artifact org.eclipse.smarthome.extension.ui:org.eclipse.smarthome.ui.classic:jar:0.9.0-SNAPSHOT
```
```
Caused by: java.io.IOException: Error resolving artifact org.eclipse.smarthome.extension.ui:org.eclipse.smarthome.ui.basic:jar:0.9.0-SNAPSHOT: Could not find artifact org.eclipse.smarthome.extension.ui:org.eclipse.smarthome.ui.basic:jar:0.9.0-SNAPSHOT
```

Are you sure that the runtime could access Maven Central?

**Comment by kirantpatil** [comment]
Sir, is there any command to check whether runtime can access Maven Central or any other way to find it ?

**Comment by maggu2810** [comment]
The Eclipse SmartHome bundles are located in the Eclipse Maven repository only, not in Maven Central (sorry about that).

The repository is not set to be used in the custom distribution.
You need to add the repository (see e.g. here: https://github.com/maggu2810/smarthome-packaging-sample-karaf/blob/70c512508c688075eeeaecfe6a5dfbbcddf89009/pom.xml#L242) in `${karaf.etc}/org.ops4j.pax.url.mvn.cfg` for the key `org.ops4j.pax.url.mvn.repositories`.
You can do that automatically using `src/main/karaf/assembly-property-edits.xml` (don't forget to set `@snapshots`).
Perhaps you should read the comments in `org.ops4j.pax.url.mvn.cfg` to get more detailed information.

If it is working you can create a PR, so other ones don't run into the same problem...
