### ISSUE TITLE
Bundle state not changed in smarthome-packaging-smaple-karaf

### ISSUE THREAD

**Issue by amarpulli544** [maggu2810/smarthome-packaging-sample-karaf#7]
Hi @maggu2810 ,

I am trying to load my bundle of jar file into deploy folder in smarthome-packaging-smaple-karaf.
When I drop my jar file into deploy folder, it will not going to Active State.
My bundle list:

```
195 | Active    |  80 | 5.0.2                 | Require-Bundle Fix :: org.objectweb.asm
201 | Active    |  80 | 2.1.0.201704141547    | HABPanel User Interface
202 | Active    |  80 | 2.0.0.b3              | openHAB Dashboard UI
204 | Active    |  80 | 2.0.0.b3              | openHAB Serial Transport Bundle
206 | Installed |  80 | 2.0.2.201706011411    | SNAVXbee2 Binding
```
It will always in Installed State.
This is the issue, when I could start the ESH Server

```
 206 - org.openhab.binding.snavxbee2 - 2.0.2.201706011411 | FrameworkEvent ERROR - org.openhab.binding.snavxbee2
org.osgi.framework.BundleException: Unable to resolve org.openhab.binding.snavxbee2 [206](R 206.0): missing requirement [org.openhab.binding.snavxbee2 [206](R 206.0)] osgi.wiring.package; (osgi.wiring.package=org.openhab.core.items) Unresolved requirements: [[org.openhab.binding.snavxbee2 [206](R 206.0)] osgi.wiring.package; (osgi.wiring.package=org.openhab.core.items)]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111)[org.apache.felix.framework-5.4.0.jar:]
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2117)[org.apache.felix.framework-5.4.0.jar:]
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)[org.apache.felix.framework-5.4.0.jar:]
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)[org.apache.felix.framework-5.4.0.jar:]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_121] 
```

My Bundle Manifest File:

```
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: SNAVXbee2 Binding
Bundle-SymbolicName: org.openhab.binding.snavxbee2;singleton:=true
Bundle-Vendor: openHAB
Bundle-Version: 2.0.2.qualifier
Bundle-RequiredExecutionEnvironment: JavaSE-1.7
Bundle-ClassPath: .
Import-Package: 
 com.google.common.collect;version="10.0.1",
 gnu.io,
 org.eclipse.smarthome.config.core,
 org.eclipse.smarthome.config.discovery,
 org.eclipse.smarthome.core.common.registry,
 org.eclipse.smarthome.core.items,
 org.eclipse.smarthome.core.library.types,
 org.eclipse.smarthome.core.thing,
 org.eclipse.smarthome.core.thing.binding,
 org.eclipse.smarthome.core.thing.binding.builder,
 org.eclipse.smarthome.core.thing.type,
 org.eclipse.smarthome.core.types,
 org.jupnp.model.meta,
 org.openhab.binding.snavxbee2,
 org.openhab.binding.snavxbee2.handler,
 org.openhab.core.items,
 org.osgi.framework;version="1.8.0",
 org.slf4j
Service-Component: OSGI-INF/*.xml
Export-Package: com.digi.xbee.api;
  uses:="com.digi.xbee.api.connection.serial,
   org.slf4j,
   com.digi.xbee.api.connection,
   com.digi.xbee.api.models,
   com.digi.xbee.api.listeners,
   com.digi.xbee.api.io,
   com.digi.xbee.api.packet",
 com.digi.xbee.api.connection;
  uses:="com.digi.xbee.api.models,
   com.digi.xbee.api.listeners,
   com.digi.xbee.api,
   com.digi.xbee.api.packet",
 com.digi.xbee.api.connection.serial;uses:="gnu.io,com.digi.xbee.api.connection",
 com.digi.xbee.api.discoverdevices;uses:="com.digi.xbee.api.listeners,com.digi.xbee.api",
 com.digi.xbee.api.exceptions;uses:="com.digi.xbee.api.models",
 com.digi.xbee.api.io,
 com.digi.xbee.api.listeners;
  uses:="com.digi.xbee.api.models,
   com.digi.xbee.api.io,
   com.digi.xbee.api.packet,
   com.digi.xbee.api",
 com.digi.xbee.api.models;uses:="com.digi.xbee.api,com.digi.xbee.api.packet",
 com.digi.xbee.api.packet;uses:="com.digi.xbee.api.models",
 com.digi.xbee.api.packet.common;uses:="com.digi.xbee.api.models,com.digi.xbee.api.io,com.digi.xbee.api.packet",
 com.digi.xbee.api.packet.raw;uses:="com.digi.xbee.api.models,com.digi.xbee.api.io,com.digi.xbee.api.packet",
 com.digi.xbee.api.utils,
 org.openhab.binding.snavxbee2;
 uses:="org.eclipse.smarthome.core.thing",
 org.openhab.binding.snavxbee2.handler;
 uses:="org.eclipse.smarthome.core.thing,org.eclipse.smarthome.core.thing.binding,org.eclipse.smarthome.core.types",
 org.openhab.binding.snavxbee2.internal;
 x-internal:=true,
 org.openhab.binding.snavxbee2.utils,
 org.openhab.binding.snavxbee2.devices 
```
What was the wrong in my bundle Manifest file.
Please let me know , I will correction my manifest file.

Thanks and Regards,
Amar.

**Comment by maggu2810** [comment]
@amarpulli544 Again, the problem you reported is not an issue with the project.
I understand that you need support with the OSGi environment at all but as told you already (e.g. https://github.com/maggu2810/smarthome-packaging-sample-karaf/issues/6#issuecomment-304677301) this is not a support forum.

The error message told you that a package cannot be resolved.
You import packages that needs to be exported by some other package.
There seems to be no package that exports the openhab stuff in your env.
